#!/bin/sh

./superbeep -n  bb4 0.5
./superbeep -n  bb4 0.5
./superbeep -n  bb4 0.5
./superbeep -n  f4 0.5

./superbeep -n  g4 0.5
./superbeep -n  g4 0.5
./superbeep -n  f4 1


./superbeep -n  d5 0.5
./superbeep -n  d5 0.5
./superbeep -n  c5 0.5
./superbeep -n  c5 0.5

./superbeep -n  bb4 1 
./superbeep -n  a0 1 # rest


./superbeep -n  bb4 0.5
./superbeep -n  bb4 0.5
./superbeep -n  bb4 0.5
./superbeep -n  f4 0.5

./superbeep -n  g4 0.5
./superbeep -n  g4 0.5
./superbeep -n  f4 1


./superbeep -n  d5 0.5
./superbeep -n  d5 0.5
./superbeep -n  c5 0.5
./superbeep -n  c5 0.5

./superbeep -n  bb4 1 
./superbeep -n  a0 1 # rest


